title: Canon Ij Printer 
description: Setup your Ij Start Canon Printer Software with canon.com/ijsetup and follow the steps to download and install the canon printer driver.
theme: jekyll-theme-tactile
